/*
 * CepteUydu - arayüz metinleri (Türkçe / English)
 * Yeni bir metin eklerken iki dile de ekleyin; `node scripts/dil-kontrol.mjs` eksikleri listeler.
 * "{n}" gibi süslü parantezli yerler t('anahtar', { n: 5 }) ile doldurulur.
 */
window.CEPTE_DIL = {
    tr: {
        'app.name': 'CepteUydu',
        'app.tagline': 'Uydu bulucu ve çanak kurulum asistanı',

        'splash.subtitle': 'Uydunu bul, çanağını dakikalar içinde doğru yöne çevir.',
        'splash.start': 'Başlayalım',

        'nav.home': 'Ana Sayfa',
        'nav.finder': 'Uydu Bulucu',
        'nav.map': 'Uydu Haritası',
        'nav.location': 'Konumum',
        'nav.compass': 'Pusula',
        'nav.level': 'Su Terazisi',
        'nav.ar': 'AR Kamera',
        'nav.channels': 'Frekans Rehberi',
        'nav.area': 'Alan Hesaplama',
        'nav.privacy': 'Gizlilik Politikası',
        'nav.back': 'Geri',
        'nav.menu': 'Menü',
        'nav.language': 'Dil',

        'home.finderDesc': 'Azimut, elevasyon ve LNB açısı + AR ile hizalama',
        'home.areaDesc': 'Haritada arazi / çatı alanını ölç (m², dönüm, hektar)',
        'home.quickEmptyTitle': 'Konumunu belirle',
        'home.quickEmptyText': 'Çanak açılarını görmek için dokun',

        'common.az': 'Az',
        'common.el': 'El',
        'common.skew': 'Skew',
        'common.elevation': 'Elevasyon',
        'common.lnbSkew': 'LNB skew',
        'common.lat': 'Enlem',
        'common.lon': 'Boylam',
        'common.apply': 'Uygula',
        'common.close': 'Kapat',
        'common.copy': 'Kopyala',
        'common.share': 'Paylaş',
        'common.retry': 'Tekrar dene',
        'common.unknown': 'Bilinmiyor',

        'dir.N': 'K', 'dir.E': 'D', 'dir.S': 'G', 'dir.W': 'B',

        'data.loading': 'Veriler yükleniyor...',
        'data.checking': 'GitHub\'da güncel veri kontrol ediliyor...',
        'data.downloading': 'Yeni veri GitHub\'dan indiriliyor...',
        'data.error': 'Veriler yüklenemedi.',
        'data.info': 'Veri: {source} · {date} · {n} kayıt',
        'data.src.github': 'GitHub (yeni indirildi)',
        'data.src.cache': 'GitHub (cihazda)',
        'data.src.bundled': 'uygulama içi',

        'tkgs.title': 'Türksat Kanal Güncelleme (TKGS)',
        'tkgs.short': 'Kanallar kaybolduysa şebeke araması',
        'tkgs.long': 'Türksat 4A / 5B / 6A · 42.0°E — Kanallar kaybolduysa alıcıda bu frekansla şebeke araması yapın. TKGS destekli alıcılar listeyi kendisi günceller.',
        'tkgs.network': 'TKGS / şebeke',
        'tkgs.alt': 'alternatif',

        'loc.useGps': 'GPS ile konumumu bul',
        'loc.locating': 'Konum alınıyor...',
        'loc.refresh': 'Konumu yenile',
        'loc.pickCity': '— veya şehir seç —',
        'loc.gpsNote': '±{acc} m doğrulukla GPS konumu',
        'loc.mapNote': 'Haritadan seçilen nokta',
        'loc.manualNote': 'Elle girilen koordinat',
        'loc.errDenied': 'Konum izni verilmedi. Ayarlardan izin verin veya şehir seçin.',
        'loc.errUnsupported': 'Bu cihaz konum servisini desteklemiyor. Şehir seçin veya koordinat girin.',
        'loc.errTimeout': 'Konum zamanında alınamadı. Açık alanda tekrar deneyin.',
        'loc.errUnavailable': 'Konum alınamadı. Konum servisinin açık olduğundan emin olun.',
        'loc.none': 'Henüz konum belirlenmedi.',
        'loc.accuracy': 'Doğruluk',
        'loc.altitude': 'Rakım',
        'loc.visibleCount': 'Görünen uydu',
        'loc.openMaps': 'Harita',
        'loc.visibleTitle': 'Buradan görünen uydular',
        'loc.visibleHelp': 'Elevasyonu 10°\'nin altındaki uydular engellere karşı çok hassastır. Hizalamak için dokunun.',
        'loc.shareText': 'Konumum: {c}',

        'find.satellite': 'Uydu',
        'find.location': 'Konum',
        'find.angles': 'Çanak açıları',
        'find.customLon': 'Listede olmayan bir konum gir',
        'find.customLonPh': 'ör. 42.0 veya -7.0',
        'find.customLonHint': 'Doğu (E) için pozitif, Batı (W) için negatif değer girin.',
        'find.customName': 'Özel konum',
        'find.pickOnMap': 'Haritadan seç',
        'find.notVisible': 'Bu uydu bulunduğunuz konumdan görünmüyor (ufkun altında).',
        'find.lowEl': 'Elevasyon çok düşük: bina ve ağaçlar sinyali kolayca keser. Yeri AR ile mutlaka kontrol edin.',
        'find.azCompass': 'Azimut (pusula)',
        'find.trueNorth': 'gerçek kuzeye göre {v}°',
        'find.aboveHorizon': 'ufuktan yukarı açı',
        'find.distance': 'Uyduya mesafe',
        'find.skewZero': 'LNB düz kalır',
        'find.skewCw': 'arkadan bakınca saat yönünde',
        'find.skewCcw': 'arkadan bakınca saat yönünün tersine',
        'find.lnbHelp': 'Çanağın arkasında durup uyduya doğru bakarken LNB\'yi şekildeki gibi döndürün. Kesik çizgi LNB\'nin düz konumudur. Son ayarı sinyal kalitesine bakarak ±5° içinde yapın.',
        'find.declination': 'Manyetik sapma: ',
        'find.declinationHelp': 'Pusulalar manyetik kuzeyi gösterir. Doğu sapma pozitiftir; Türkiye\'de yaklaşık +5° ile +7° arasındadır.',
        'find.offsetNote': 'Ofset (oval) çanaklarda yansıtıcı yüzey elevasyondan yaklaşık 20–26° daha dik durur; ayaktaki elevasyon skalasını kullanın.',
        'find.openAr': 'AR ile uyduyu bul ve engel kontrolü yap',
        'find.arHelp': 'Kamera, konum ve hareket sensörü izni istenir. Telefonu metal yüzeylerden uzak tutun, pusulayı havada "8" çizerek kalibre edin.',
        'find.needLocation': 'Açıları görmek için konumunuzu belirleyin.',

        'ar.target': 'Hedef',
        'ar.phone': 'Telefon',
        'ar.waiting': 'Sensörler bekleniyor...',
        'ar.locked': 'Uydu yönündesiniz — önünde engel var mı?',
        'ar.almost': 'Neredeyse...',
        'ar.right': 'Sağa {n}°',
        'ar.left': 'Sola {n}°',
        'ar.up': 'Yukarı {n}°',
        'ar.down': 'Aşağı {n}°',
        'ar.deviation': 'Sapma: {v}°',
        'ar.beep': 'Bip',
        'ar.calibration': 'Kalibrasyon',
        'ar.beltLegend': 'Kesikli çizgi: Clarke kuşağı (uyduların dizildiği yay)',
        'ar.trim': 'Pusula ince ayarı',
        'ar.fov': 'Kamera görüş açısı',
        'ar.tuneHelp': 'Yönü bilinen bir noktaya (ör. çevrede doğru kurulmuş bir çanağın baktığı yöne) göre ince ayar yapabilirsiniz.',
        'ar.noSensor': 'Yön sensörü verisi alınamadı. Bu özellik pusulası olan bir telefonda çalışır.',
        'ar.noAbs': 'Bu cihaz mutlak pusula verisi vermiyor; yön tahmini hatalı olabilir.',
        'ar.noPermission': 'Hareket ve yön sensörü izni verilmedi. Ayarlardan izin verip tekrar deneyin.',
        'ar.camUnsupported': 'Bu cihazda kamera kullanılamıyor; yönlendirme kamerasız devam ediyor.',
        'ar.camDenied': 'Kamera izni verilmedi; yönlendirme kamerasız devam ediyor.',
        'ar.camFailed': 'Kamera açılamadı; yönlendirme kamerasız devam ediyor.',

        'map.tapHint': 'Çanağın kurulacağı yere dokunun',
        'map.noLocation': 'Konum seçmek için haritaya dokunun veya GPS düğmesine basın.',
        'map.trueNorthNote': 'Mor çizgi çanağın bakacağı yönü gösterir (gerçek kuzeye göre).',

        'compass.magnetic': 'manyetik {v}°',
        'compass.holdFlat': 'Telefonu yere paralel tutun. Pusulayı havada "8" çizerek kalibre edin.',
        'compass.start': 'Sensörleri başlat',
        'compass.targetTitle': 'Seçili uydu',
        'compass.onTarget': 'Uydu yönündesiniz ✓',
        'compass.declNote': 'Gösterilen yön gerçek kuzeye göredir (manyetik sapma {v}°).',

        'level.modeLevel': 'Su terazisi',
        'level.modeIncline': 'Açı ölçer',
        'level.tiltX': 'Sağa/sola eğim',
        'level.tiltY': 'Öne/arkaya eğim',
        'level.calibrate': 'Sıfırla (kalibre et)',
        'level.reset': 'Fabrika ayarı',
        'level.levelHelp': 'Telefonu çanak ayağının veya direğin üst yüzeyine düz yatırın. Kabarcık ortada ve halka yeşilse yüzey düzdür.',
        'level.inclineHelp': 'Telefonun uzun kenarını açısını ölçmek istediğiniz parçaya yaslayın. Yeşil kesikli çizgi seçili uydunun elevasyonudur.',
        'level.targetEl': 'Hedef elevasyon {v}°',
        'level.noSensor': 'Eğim sensörü verisi alınamadı.',

        'area.hint': 'Alanın köşelerine sırayla dokunun',
        'area.m2': 'm²',
        'area.unit2': 'Dönüm',
        'area.ha': 'Hektar',
        'area.points': '{n} nokta',
        'area.perimeter': 'çevre {v} m',
        'area.undo': 'Geri al',
        'area.clear': 'Temizle',

        'ch.searchAll': 'Uydu, kanal, frekans veya ülke ara...',
        'ch.searchIn': 'Kanal, frekans, ülke veya şifreleme ara...',
        'ch.statSats': 'Uydu',
        'ch.statActive': 'Aktif yayın',
        'ch.statTotal': 'Toplam kayıt',
        'ch.archive': 'Arşiv',
        'ch.archiveTitle': 'Pasif / Eski Yayınlar',
        'ch.records': '{n} kayıtlı yayın',
        'ch.activeN': '{n} aktif',
        'ch.matches': '{n} eşleşen kanal',
        'ch.alignThis': 'Bu uyduya çanak hizala',
        'ch.noSat': 'Aramanıza uygun uydu veya kanal bulunamadı.',
        'ch.listing': '{n} yayın listeleniyor',
        'ch.all': 'Tümü',
        'ch.active': 'Aktif',
        'ch.passive': 'Pasif',
        'ch.allCats': 'Tüm kategoriler',
        'ch.catHint': 'Kategoriler kanal adından tahmin edilir',
        'ch.activeBadge': 'Aktif yayın',
        'ch.passiveBadge': 'Pasif / yayın dışı',
        'ch.copyTuning': 'Ayar bilgisini kopyala',
        'ch.enc': 'Şifre',
        'ch.fta': 'Şifresiz',
        'ch.more': 'Daha fazla göster ({n} kaldı)',
        'ch.noChannel': 'Aradığınız kriterlere uygun kanal bulunamadı.',

        'cat.spor': 'Spor', 'cat.haber': 'Haber', 'cat.belgesel': 'Belgesel', 'cat.film': 'Film & Dizi',
        'cat.cocuk': 'Çocuk', 'cat.muzik': 'Müzik', 'cat.radyo': 'Radyo', 'cat.uhd': '4K / UHD', 'cat.hd': 'HD',
    },

    en: {
        'app.name': 'CepteUydu',
        'app.tagline': 'Satellite finder & dish setup assistant',

        'splash.subtitle': 'Find your satellite and point your dish the right way in minutes.',
        'splash.start': 'Get Started',

        'nav.home': 'Home',
        'nav.finder': 'Satellite Finder',
        'nav.map': 'Satellite Map',
        'nav.location': 'My Location',
        'nav.compass': 'Compass',
        'nav.level': 'Leveler',
        'nav.ar': 'AR Camera',
        'nav.channels': 'Frequency Guide',
        'nav.area': 'Area Calculator',
        'nav.privacy': 'Privacy Policy',
        'nav.back': 'Back',
        'nav.menu': 'Menu',
        'nav.language': 'Language',

        'home.finderDesc': 'Azimuth, elevation and LNB skew + AR alignment',
        'home.areaDesc': 'Measure land or roof area on the map (m², acres, hectares)',
        'home.quickEmptyTitle': 'Set your location',
        'home.quickEmptyText': 'Tap to see your dish angles',

        'common.az': 'Az',
        'common.el': 'El',
        'common.skew': 'Skew',
        'common.elevation': 'Elevation',
        'common.lnbSkew': 'LNB skew',
        'common.lat': 'Latitude',
        'common.lon': 'Longitude',
        'common.apply': 'Apply',
        'common.close': 'Close',
        'common.copy': 'Copy',
        'common.share': 'Share',
        'common.retry': 'Try again',
        'common.unknown': 'Unknown',

        'dir.N': 'N', 'dir.E': 'E', 'dir.S': 'S', 'dir.W': 'W',

        'data.loading': 'Loading data...',
        'data.checking': 'Checking GitHub for updated data...',
        'data.downloading': 'Downloading new data from GitHub...',
        'data.error': 'Could not load data.',
        'data.info': 'Data: {source} · {date} · {n} records',
        'data.src.github': 'GitHub (just downloaded)',
        'data.src.cache': 'GitHub (on device)',
        'data.src.bundled': 'built-in',

        'tkgs.title': 'Türksat Channel Update (TKGS)',
        'tkgs.short': 'Network scan if channels are lost',
        'tkgs.long': 'Türksat 4A / 5B / 6A · 42.0°E — If channels disappear, run a network scan on your receiver with this frequency. TKGS-capable receivers update the list automatically.',
        'tkgs.network': 'TKGS / network',
        'tkgs.alt': 'alternative',

        'loc.useGps': 'Find my location (GPS)',
        'loc.locating': 'Getting location...',
        'loc.refresh': 'Refresh location',
        'loc.pickCity': '— or pick a city —',
        'loc.gpsNote': 'GPS location, ±{acc} m accuracy',
        'loc.mapNote': 'Point picked on the map',
        'loc.manualNote': 'Manually entered coordinates',
        'loc.errDenied': 'Location permission denied. Allow it in settings or pick a city.',
        'loc.errUnsupported': 'This device does not support location. Pick a city or enter coordinates.',
        'loc.errTimeout': 'Location timed out. Try again in an open area.',
        'loc.errUnavailable': 'Could not get location. Make sure location services are on.',
        'loc.none': 'No location set yet.',
        'loc.accuracy': 'Accuracy',
        'loc.altitude': 'Altitude',
        'loc.visibleCount': 'Visible satellites',
        'loc.openMaps': 'Map',
        'loc.visibleTitle': 'Satellites visible from here',
        'loc.visibleHelp': 'Satellites below 10° elevation are very sensitive to obstacles. Tap one to align.',
        'loc.shareText': 'My location: {c}',

        'find.satellite': 'Satellite',
        'find.location': 'Location',
        'find.angles': 'Dish angles',
        'find.customLon': 'Enter a position not in the list',
        'find.customLonPh': 'e.g. 42.0 or -7.0',
        'find.customLonHint': 'Use positive values for East (E) and negative for West (W).',
        'find.customName': 'Custom position',
        'find.pickOnMap': 'Pick on map',
        'find.notVisible': 'This satellite is not visible from your location (below the horizon).',
        'find.lowEl': 'Very low elevation: buildings and trees easily block the signal. Check the spot with AR first.',
        'find.azCompass': 'Azimuth (compass)',
        'find.trueNorth': '{v}° from true north',
        'find.aboveHorizon': 'angle above the horizon',
        'find.distance': 'Distance to satellite',
        'find.skewZero': 'keep the LNB level',
        'find.skewCw': 'clockwise, seen from behind',
        'find.skewCcw': 'counter-clockwise, seen from behind',
        'find.lnbHelp': 'Standing behind the dish and looking towards the satellite, rotate the LNB as shown. The dashed line is the LNB\'s level position. Fine-tune within ±5° using signal quality.',
        'find.declination': 'Magnetic declination: ',
        'find.declinationHelp': 'Compasses point to magnetic north. East declination is positive; in Türkiye it is about +5° to +7°.',
        'find.offsetNote': 'On offset (oval) dishes the reflector stands about 20–26° steeper than the elevation; use the elevation scale on the mount.',
        'find.openAr': 'Find the satellite with AR & check for obstacles',
        'find.arHelp': 'Camera, location and motion permissions are requested. Keep the phone away from metal and calibrate the compass by drawing a figure "8" in the air.',
        'find.needLocation': 'Set your location to see the angles.',

        'ar.target': 'Target',
        'ar.phone': 'Phone',
        'ar.waiting': 'Waiting for sensors...',
        'ar.locked': 'On target — any obstacles in front?',
        'ar.almost': 'Almost there...',
        'ar.right': 'Right {n}°',
        'ar.left': 'Left {n}°',
        'ar.up': 'Up {n}°',
        'ar.down': 'Down {n}°',
        'ar.deviation': 'Off by {v}°',
        'ar.beep': 'Beep',
        'ar.calibration': 'Calibration',
        'ar.beltLegend': 'Dashed line: Clarke belt (where satellites sit)',
        'ar.trim': 'Compass fine-tune',
        'ar.fov': 'Camera field of view',
        'ar.tuneHelp': 'You can fine-tune against a known direction, e.g. where a correctly installed dish nearby is pointing.',
        'ar.noSensor': 'No orientation sensor data. This feature needs a phone with a compass.',
        'ar.noAbs': 'This device does not provide absolute compass data; direction may be inaccurate.',
        'ar.noPermission': 'Motion and orientation permission was denied. Allow it in settings and try again.',
        'ar.camUnsupported': 'Camera is not available on this device; guidance continues without it.',
        'ar.camDenied': 'Camera permission denied; guidance continues without the camera.',
        'ar.camFailed': 'Could not open the camera; guidance continues without it.',

        'map.tapHint': 'Tap where the dish will be installed',
        'map.noLocation': 'Tap the map or press the GPS button to choose a location.',
        'map.trueNorthNote': 'The purple line shows where the dish should point (true north).',

        'compass.magnetic': 'magnetic {v}°',
        'compass.holdFlat': 'Hold the phone parallel to the ground. Calibrate by drawing a figure "8" in the air.',
        'compass.start': 'Start sensors',
        'compass.targetTitle': 'Selected satellite',
        'compass.onTarget': 'Facing the satellite ✓',
        'compass.declNote': 'Heading is shown relative to true north (magnetic declination {v}°).',

        'level.modeLevel': 'Bubble level',
        'level.modeIncline': 'Inclinometer',
        'level.tiltX': 'Left/right tilt',
        'level.tiltY': 'Front/back tilt',
        'level.calibrate': 'Set zero (calibrate)',
        'level.reset': 'Reset',
        'level.levelHelp': 'Lay the phone flat on top of the mount or mast. The surface is level when the bubble is centred and the ring turns green.',
        'level.inclineHelp': 'Rest the phone\'s long edge against the part you want to measure. The green dashed line is the selected satellite\'s elevation.',
        'level.targetEl': 'Target elevation {v}°',
        'level.noSensor': 'No tilt sensor data available.',

        'area.hint': 'Tap the corners of the area in order',
        'area.m2': 'm²',
        'area.unit2': 'Acres',
        'area.ha': 'Hectares',
        'area.points': '{n} points',
        'area.perimeter': 'perimeter {v} m',
        'area.undo': 'Undo',
        'area.clear': 'Clear',

        'ch.searchAll': 'Search satellite, channel, frequency or country...',
        'ch.searchIn': 'Search channel, frequency, country or encryption...',
        'ch.statSats': 'Satellites',
        'ch.statActive': 'Active channels',
        'ch.statTotal': 'Total records',
        'ch.archive': 'Archive',
        'ch.archiveTitle': 'Inactive / Old Channels',
        'ch.records': 'Channels: {n}',
        'ch.activeN': '{n} active',
        'ch.matches': '{n} matching channels',
        'ch.alignThis': 'Align dish to this satellite',
        'ch.noSat': 'No satellites or channels match your search.',
        'ch.listing': 'Showing {n} channels',
        'ch.all': 'All',
        'ch.active': 'Active',
        'ch.passive': 'Inactive',
        'ch.allCats': 'All categories',
        'ch.catHint': 'Categories are guessed from channel names',
        'ch.activeBadge': 'On air',
        'ch.passiveBadge': 'Inactive / off air',
        'ch.copyTuning': 'Copy tuning info',
        'ch.enc': 'Encryption',
        'ch.fta': 'FTA',
        'ch.more': 'Show more ({n} left)',
        'ch.noChannel': 'No channels match your filters.',

        'cat.spor': 'Sports', 'cat.haber': 'News', 'cat.belgesel': 'Documentary', 'cat.film': 'Movies & Series',
        'cat.cocuk': 'Kids', 'cat.muzik': 'Music', 'cat.radyo': 'Radio', 'cat.uhd': '4K / UHD', 'cat.hd': 'HD',
    },
};
